syntax error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,42 +24,42 @@ inputs:
 runs:
   using: 'composite'
   steps:
-  - name: Check Runner OS
-    if: ${{ runner.os != 'Linux' }}
-    shell: bash
-    run: |
-      echo "::error title=⛔ error hint::Support Linux Only"
-      exit 1
-  - name: Install Molnctl
-    shell: bash
-    env:
-      GH_TOKEN: ${{ github.token }}
-      VERSION: ${{ inputs.version }}
-      MOLNETT_CLIENT_ID: ${{ inputs.api-token-client-id }}
-      MOLNETT_CLIENT_SECRET: ${{ inputs.api-token-client-secret }}
-      MOLNETT_API_URL: https://api.${{ inputs.cell }}.molnett.app
-      CELL: ${{ inputs.cell }}
-    run: |
-      gh release download --repo molnett/molnctl -p 'molnctl*' $VERSION
-      chmod +x molnctl-x86_64-unknown-linux-gnu
-      sudo mv molnctl-x86_64-unknown-linux-gnu /usr/bin/molnctl
-      mkdir ~/.config/molnett
-      MOLNETT_TOKEN=$(curl https://auth.$CELL.molnett.app/oauth2/token -X POST --data "client_id=$MOLNETT_CLIENT_ID&grant_type=client_credentials&client_secret=$MOLNETT_CLIENT_SECRET" | jq -r .access_token)
-      EXPIRY=$(date -u -d "+24 hours" +"%Y-%m-%dT%H:%M:%S.%NZ")
-      cat << EOF > ~/.config/molnett/config.json
-      {
-        "token": {
-          "access_token": "$MOLNETT_TOKEN",
-          "refresh_token": null,
-          "expiry": "$EXPIRY"
-        },
-        "url": "$MOLNETT_API_URL"
-      }
-      EOF
-      molnctl orgs list
-      echo "molnctl sucessfully installed!"
-  - name: Set Default Org
-    shell: bash
-    env:
-      ORG: ${{ inputs.default-org }}
-    run: molnctl orgs switch $ORG
+    - name: Check Runner OS
+      if: ${{ runner.os != 'Linux' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::Support Linux Only"
+        exit 1
+    - name: Install Molnctl
+      shell: bash
+      env:
+        GH_TOKEN: ${{ github.token }}
+        VERSION: ${{ inputs.version }}
+        MOLNETT_CLIENT_ID: ${{ inputs.api-token-client-id }}
+        MOLNETT_CLIENT_SECRET: ${{ inputs.api-token-client-secret }}
+        MOLNETT_API_URL: https://api.${{ inputs.cell }}.molnett.app
+        CELL: ${{ inputs.cell }}
+      run: |
+        gh release download --repo molnett/molnctl -p 'molnctl*' $VERSION
+        chmod +x molnctl-x86_64-unknown-linux-gnu
+        sudo mv molnctl-x86_64-unknown-linux-gnu /usr/bin/molnctl
+        mkdir ~/.config/molnett
+        MOLNETT_TOKEN=$(curl https://auth.$CELL.molnett.app/oauth2/token -X POST --data "client_id=$MOLNETT_CLIENT_ID&grant_type=client_credentials&client_secret=$MOLNETT_CLIENT_SECRET" | jq -r .access_token)
+        EXPIRY=$(date -u -d "+24 hours" +"%Y-%m-%dT%H:%M:%S.%NZ")
+        cat << EOF > ~/.config/molnett/config.json
+        {
+          "token": {
+            "access_token": "$MOLNETT_TOKEN",
+            "refresh_token": null,
+            "expiry": "$EXPIRY"
+          },
+          "url": "$MOLNETT_API_URL"
+        }
+        EOF
+        molnctl orgs list
+        echo "molnctl sucessfully installed!"
+    - name: Set Default Org
+      shell: bash
+      env:
+        ORG: ${{ inputs.default-org }}
+      run: molnctl orgs switch $ORG
